'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Bookloan1

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''loanID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loanID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantoremail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantoremail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantor2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantorName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantorName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantoremail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantoremail2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantor3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantorName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantorName3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''guarantoremail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents guarantoremail3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTerms As Global.System.Web.UI.WebControls.CheckBox
End Class
